steps:
  # Use buildpacks to create a container
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args:
      - 'build'
      - 'gcr.io/${PROJECT_ID}/carflow-api:${COMMIT_SHA}'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--publish'
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'carflow-api'
      - '--image=gcr.io/${PROJECT_ID}/carflow-api:${COMMIT_SHA}'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=128Mi'
      - '--cpu=1'
      - '--max-instances=1'
      - '--min-instances=0'
      - '--timeout=30s'
      - '--set-env-vars=PORT=8080'

images:
  - 'gcr.io/${PROJECT_ID}/carflow-api:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY 