name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'simple-app/**'
      - '.github/workflows/cloud-run-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy carflow-api \
          --source ./simple-app \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --memory 128Mi \
          --cpu 1 \
          --max-instances 1 \
          --min-instances 0 \
          --timeout 30s
        
    - name: Get Service URL
      id: get-url
      run: |
        SERVICE_URL=$(gcloud run services describe carflow-api --region us-central1 --format 'value(status.url)')
        echo "::set-output name=url::$SERVICE_URL"
        
    - name: Test Deployment
      run: |
        sleep 10  # Give time for deployment to finalize
        curl -f "${{ steps.get-url.outputs.url }}/cars" || exit 1
        
    - name: Show Output
      run: echo "Deployed to ${{ steps.get-url.outputs.url }}" 