name: Deploy UI to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'cmd/ui/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build UI Static Assets
        run: |
          mkdir -p build
          cp -r cmd/ui/templates/* build/
          # If we had to compile assets, we'd do that here

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 